### ISSUE TITLE
 manage.py migrate: error: unrecognized arguments: --no-input

### ISSUE THREAD

**Issue by sakib5271** [dotja/django-docker-compose#1]
tried docker compose in windows 
getting the following error

 manage.py migrate: error: unrecognized arguments: --no-input

something related to line ending error.

**Comment by dotja** [comment]
Thanks, I will take a look. Note that I wasn't running Windows for this repo.

**Comment by sakib5271** [comment]
Solved it.

We have change CRLF to LF and save the bash script again. A windows to linux shift issue. for line ending.
